data: # Data configuration
  csv_file: 'datasets\monocyte_reassigned.csv' # Path to the data CSV file (str)
  type: 'monocyte_clinical'

training: # Training configuration 
  num_epochs: 100 # Number of epochs (int)
  batch_size: 64 # Batch size (int)
  learning_rate: 5e-5 # Learning rate for Adam (float)
  learning_rate_end: 0.0001 # End learning rate for scheduler (float)
  weight_decay: 1e-4 # Weight decay for SGD (float)
  momentum: 0.9 # Momentum for SGD (float)

model: # Model configuration
  image_size: 352 # Image size (int)
  use_scheduler: False # Use learning rate scheduler (bool)
  num_workers: 8 # Number of workers for data loader (int)
